name: Build and Release Wheel

on:
  push:
    branches:
      - main

permissions:
  contents: write # Required to create releases and tags

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.10"
          enable-cache: true

      - name: Verify uv installation
        run: uv --version

      - name: Set up Python
        run: uv python install

      - name: Build wheel with uv
        run: uv build

      - name: Get package version
        id: get_version
        run: |
          uv venv
          uv pip install toml # Install toml parser using uv
          version=$(uv run python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "Detected version: ${version}"

      - name: Create GitHub Release and Upload Wheel
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          generate_release_notes: true
          files: ./dist/*.whl # Upload all .whl files found in the dist directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}